import { NavLink, Route, Routes } from 'react-router-dom'
import { MetaProvider, useMeta } from './lib/MetaContext'
import Overview from './pages/Overview'
import LapTimes from './pages/LapTimes'
import Telemetry from './pages/Telemetry'
import DriverBehavior from './pages/DriverBehavior'
import TireDegradation from './pages/TireDegradation'
import DataQuality from './pages/DataQuality'

const NAV_ITEMS = [
  { to: '/', label: 'Overview', end: true },
  { to: '/laps', label: 'Lap Times & Strategy' },
  { to: '/telemetry', label: 'Telemetry' },
  { to: '/drivers', label: 'Driver Behavior' },
  { to: '/tires', label: 'Tire Degradation' },
  { to: '/quality', label: 'Data Quality' },
]

function Header() {
  const { meta } = useMeta()
  return (
    <header className="sticky top-0 z-20 border-b border-border bg-bg/90 backdrop-blur-md">
      <div className="max-w-[1400px] mx-auto px-6 pt-4">
        <div className="flex items-center justify-between gap-6 pb-3">
          <div className="flex items-center gap-3">
            <div className="h-8 w-8 rounded-lg bg-f1-red flex items-center justify-center font-black text-white text-sm shrink-0">
              F1
            </div>
            <div>
              <h1 className="text-base font-bold text-gray-50 leading-tight">F1DatasetMaker</h1>
              <p className="text-xs text-gray-500 leading-tight">
                {meta ? `${meta.event_name} · ${meta.circuit}, ${meta.country}` : 'Loading session…'}
              </p>
            </div>
          </div>
          {meta?.synthetic && (
            <span className="hidden sm:inline-flex items-center gap-1.5 rounded-full border border-amber-800/50 bg-amber-950/40 px-3 py-1 text-xs font-medium text-amber-300">
              <span className="h-1.5 w-1.5 rounded-full bg-amber-400" />
              Synthetic demo data — fictional teams &amp; drivers
            </span>
          )}
        </div>
        <nav className="flex gap-1 -mb-px overflow-x-auto">
          {NAV_ITEMS.map((item) => (
            <NavLink
              key={item.to}
              to={item.to}
              end={item.end}
              className={({ isActive }) =>
                `px-3.5 py-2.5 text-sm font-medium whitespace-nowrap border-b-2 transition-colors ${
                  isActive
                    ? 'border-f1-red text-gray-50'
                    : 'border-transparent text-gray-500 hover:text-gray-300 hover:border-gray-700'
                }`
              }
            >
              {item.label}
            </NavLink>
          ))}
        </nav>
      </div>
    </header>
  )
}

function App() {
  return (
    <MetaProvider>
      <div className="min-h-screen">
        <Header />
        <main className="max-w-[1400px] mx-auto px-6 py-6">
          <Routes>
            <Route path="/" element={<Overview />} />
            <Route path="/laps" element={<LapTimes />} />
            <Route path="/telemetry" element={<Telemetry />} />
            <Route path="/drivers" element={<DriverBehavior />} />
            <Route path="/tires" element={<TireDegradation />} />
            <Route path="/quality" element={<DataQuality />} />
          </Routes>
        </main>
        <footer className="max-w-[1400px] mx-auto px-6 pb-8 pt-4 text-xs text-gray-600">
          Generated by the F1DatasetMaker pipeline. Swap synthetic data for real OpenF1/FastF1 ingestion by running{' '}
          <code className="text-gray-500">f1dataset backfill</code> then <code className="text-gray-500">f1dataset build-features</code>.
        </footer>
      </div>
    </MetaProvider>
  )
}

export default App
